import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Archivo } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar/navbar";
import Menu from "@/components/main-layout/menu";
import ReactQueryProvider from "@/components/provider/ReactQueryProvider";
import { ModalProvider } from "@/context/model-context";
import ModalRenderer from "@/components/global/modal-renderer";


// Font setup
const archivo = Archivo({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
  variable: "--font-archivo",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="h-full w-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${archivo.variable} antialiased bg-black h-full flex flex-col m-0 p-0`}
      >
        <div className="h-[8%] w-full">
          <Navbar />
        </div>
        <div className="h-[2%]"></div>
        <section className="h-[90%] w-full overflow-hidden flex gap-11">
        
          <div className="h-full w-[12%] bg-black/1    rounded-br-3xl flex flex-col items-start justify-start px-4 py-6 space-y-2">
      
            <Menu />
      
          </div>
          <div className="h-full w-[80%] overflow-auto">
            <ReactQueryProvider >
                <ModalProvider>
                  {children}
                  <ModalRenderer />
                </ModalProvider>
            </ReactQueryProvider>

          </div>
        </section>

      </body>
    </html>
  );
}
